# Generated by Django 5.1.6 on 2025-02-21 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0011_likereply_reply_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likedposts', through='a_posts.LikedPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
