# Generated by Django 5.1.6 on 2025-02-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.FileField(null=True, upload_to='post_content'),
        ),
    ]
