# Generated by Django 5.1.6 on 2025-02-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0013_post_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='media',
        ),
    ]
