# Generated by Django 5.1.6 on 2025-02-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0015_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
