# Generated by Django 5.1.6 on 2025-02-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
