# Generated by Django 5.1.6 on 2025-02-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
